"""add column in ordertable orders columns size,color,quantity

Revision ID: 160b3a8226cb
Revises: 35dc12096d0d
Create Date: 2022-02-15 18:08:13.387196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160b3a8226cb'
down_revision = '35dc12096d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_has_products', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('orders_has_products', sa.Column('color', sa.String(length=50), nullable=False))
    op.add_column('orders_has_products', sa.Column('size', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders_has_products', 'size')
    op.drop_column('orders_has_products', 'color')
    op.drop_column('orders_has_products', 'quantity')
    # ### end Alembic commands ###
