"""create table types_sales

Revision ID: 46a92d992acf
Revises: 590946608449
Create Date: 2022-04-01 16:21:52.361686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a92d992acf'
down_revision = '590946608449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('types_sales',
    sa.Column('id_type_sale', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id_type_sale')
    )
    op.add_column('orders_has_products', sa.Column('id_type_sale', sa.Integer(), nullable=False))
    op.alter_column('orders_has_products', 'sale_value',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.create_foreign_key(None, 'orders_has_products', 'types_sales', ['id_type_sale'], ['id_type_sale'])
    op.alter_column('products', 'cost_value',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('products', 'sale_value_varejo',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('products', 'sale_value_atacado',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('products', 'sale_value_promotion',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'sale_value_promotion',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('products', 'sale_value_atacado',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('products', 'sale_value_varejo',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('products', 'cost_value',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_constraint(None, 'orders_has_products', type_='foreignkey')
    op.alter_column('orders_has_products', 'sale_value',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('orders_has_products', 'id_type_sale')
    op.drop_table('types_sales')
    # ### end Alembic commands ###
