"""add table product and variation base

Revision ID: 525b9b3212b7
Revises: cfba45427092
Create Date: 2022-02-19 13:30:18.111659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525b9b3212b7'
down_revision = 'cfba45427092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_base',
    sa.Column('id_product', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_product', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.Column('cost_value', sa.Float(precision=2), nullable=False),
    sa.Column('sale_value_varejo', sa.Float(precision=2), nullable=False),
    sa.Column('sale_value_atacado', sa.Float(precision=2), nullable=False),
    sa.Column('quantity_atacado', sa.Integer(), nullable=False),
    sa.Column('sale_value_promotion', sa.Float(precision=2), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_category'], ['categorys.id_category'], ),
    sa.PrimaryKeyConstraint('id_product'),
    sa.UniqueConstraint('code_product')
    )
    op.create_table('variations_base',
    sa.Column('id_variation', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('image', sa.String(length=150), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_product'], ['products_base.id_product'], ),
    sa.PrimaryKeyConstraint('id_variation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variations_base')
    op.drop_table('products_base')
    # ### end Alembic commands ###
