"""variation.color move for products.color

Revision ID: 590946608449
Revises: 
Create Date: 2022-03-20 15:20:37.714742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590946608449'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorys',
    sa.Column('id_category', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_category'),
    sa.UniqueConstraint('name')
    )
    op.create_table('clients',
    sa.Column('id_client', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.String(length=9), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('phone', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('birthdate', sa.DateTime(), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.PrimaryKeyConstraint('id_client'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('stores',
    sa.Column('id_store', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_store', sa.String(length=50), nullable=False),
    sa.Column('street', sa.String(length=150), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.String(length=9), nullable=False),
    sa.Column('other_information', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id_store'),
    sa.UniqueConstraint('name_store')
    )
    op.create_table('types_users',
    sa.Column('id_type_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_type_user', sa.String(length=20), nullable=False),
    sa.Column('permission', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_type_user')
    )
    op.create_table('products',
    sa.Column('id_product', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_product', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.Column('cost_value', sa.Float(precision=2), nullable=False),
    sa.Column('sale_value_varejo', sa.Float(precision=2), nullable=False),
    sa.Column('sale_value_atacado', sa.Float(precision=2), nullable=False),
    sa.Column('quantity_atacado', sa.Integer(), nullable=False),
    sa.Column('sale_value_promotion', sa.Float(precision=2), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('id_store', sa.Integer(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('image_name', sa.Text(), nullable=True),
    sa.Column('image_mimeType', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_category'], ['categorys.id_category'], ),
    sa.ForeignKeyConstraint(['id_store'], ['stores.id_store'], ),
    sa.PrimaryKeyConstraint('id_product'),
    sa.UniqueConstraint('code_product')
    )
    op.create_table('sellers',
    sa.Column('id_seller', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_resignation', sa.DateTime(), nullable=True),
    sa.Column('id_store', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_store'], ['stores.id_store'], ),
    sa.PrimaryKeyConstraint('id_seller')
    )
    op.create_table('group_products',
    sa.Column('id_group', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_product_one', sa.Integer(), nullable=False),
    sa.Column('id_product_two', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_product_one'], ['products.id_product'], ),
    sa.ForeignKeyConstraint(['id_product_two'], ['products.id_product'], ),
    sa.PrimaryKeyConstraint('id_group'),
    sa.UniqueConstraint('id_product_one'),
    sa.UniqueConstraint('id_product_two')
    )
    op.create_table('orders',
    sa.Column('id_order', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.Column('id_seller', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=True),
    sa.Column('id_store', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.ForeignKeyConstraint(['id_seller'], ['sellers.id_seller'], ),
    sa.ForeignKeyConstraint(['id_store'], ['stores.id_store'], ),
    sa.PrimaryKeyConstraint('id_order')
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('id_desabled', sa.Integer(), nullable=True),
    sa.Column('id_type_user', sa.Integer(), nullable=True),
    sa.Column('id_seller', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_seller'], ['sellers.id_seller'], ),
    sa.ForeignKeyConstraint(['id_type_user'], ['types_users.id_type_user'], ),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('variations',
    sa.Column('id_variation', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_product'], ['products.id_product'], ),
    sa.PrimaryKeyConstraint('id_variation')
    )
    op.create_table('disabled',
    sa.Column('id_disabled', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('date_disabled', sa.DateTime(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_disabled')
    )
    op.create_table('orders_has_products',
    sa.Column('id_order_has_products', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_value', sa.Float(precision=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('size', sa.String(length=10), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_order'], ['orders.id_order'], ),
    sa.ForeignKeyConstraint(['id_product'], ['products.id_product'], ),
    sa.PrimaryKeyConstraint('id_order_has_products')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_has_products')
    op.drop_table('disabled')
    op.drop_table('variations')
    op.drop_table('users')
    op.drop_table('orders')
    op.drop_table('group_products')
    op.drop_table('sellers')
    op.drop_table('products')
    op.drop_table('types_users')
    op.drop_table('stores')
    op.drop_table('clients')
    op.drop_table('categorys')
    # ### end Alembic commands ###
