"""create table relationship of orders and products relationship N,N

Revision ID: 5e898fcf4e5d
Revises: fbd3a7fbe9b5
Create Date: 2022-02-15 16:55:20.725571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e898fcf4e5d'
down_revision = 'fbd3a7fbe9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_has_products',
    sa.Column('id_order_has_products', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_value', sa.Float(precision=2), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_order'], ['orders.id_order'], ),
    sa.ForeignKeyConstraint(['id_product'], ['products.id_product'], ),
    sa.PrimaryKeyConstraint('id_order_has_products')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_has_products')
    # ### end Alembic commands ###
