"""add column quantity_migrate

Revision ID: 63861db0b777
Revises: a81ac195772a
Create Date: 2022-02-15 20:51:40.915274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63861db0b777'
down_revision = 'a81ac195772a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity_atacado', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'quantity_atacado')
    # ### end Alembic commands ###
