"""create table products, categorys and variations

Revision ID: 7ffd71ed743f
Revises: 
Create Date: 2022-02-14 18:22:44.971582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ffd71ed743f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorys',
    sa.Column('id_category', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_category'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stores',
    sa.Column('id_store', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_store', sa.String(length=50), nullable=False),
    sa.Column('adress', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_store')
    )
    op.create_table('types_users',
    sa.Column('id_type_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_type_user', sa.String(length=20), nullable=False),
    sa.Column('permission', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_type_user')
    )
    op.create_table('products',
    sa.Column('id_product', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_product', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('cost_value', sa.Float(precision=2), nullable=False),
    sa.Column('sale_value', sa.Float(precision=2), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_category'], ['categorys.id_category'], ),
    sa.PrimaryKeyConstraint('id_product'),
    sa.UniqueConstraint('code_product')
    )
    op.create_table('sellers',
    sa.Column('id_seller', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_resignation', sa.DateTime(), nullable=True),
    sa.Column('id_store', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_store'], ['stores.id_store'], ),
    sa.PrimaryKeyConstraint('id_seller')
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('id_desabled', sa.Integer(), nullable=True),
    sa.Column('id_type_user', sa.Integer(), nullable=True),
    sa.Column('id_seller', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_seller'], ['sellers.id_seller'], ),
    sa.ForeignKeyConstraint(['id_type_user'], ['types_users.id_type_user'], ),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('variations',
    sa.Column('id_variation', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('image', sa.String(length=150), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_product'], ['products.id_product'], ),
    sa.PrimaryKeyConstraint('id_variation')
    )
    op.create_table('disabled',
    sa.Column('id_disabled', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('date_disabled', sa.DateTime(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_disabled')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disabled')
    op.drop_table('variations')
    op.drop_table('users')
    op.drop_table('sellers')
    op.drop_table('products')
    op.drop_table('types_users')
    op.drop_table('stores')
    op.drop_table('categorys')
    # ### end Alembic commands ###
