"""in table group_products add foreingkeys

Revision ID: 8fba7f4a762a
Revises: 63861db0b777
Create Date: 2022-02-18 16:29:32.655436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fba7f4a762a'
down_revision = '63861db0b777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'group_products', 'products', ['id_product_one'], ['id_product'])
    op.create_foreign_key(None, 'group_products', 'products', ['id_product_two'], ['id_product'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_products', type_='foreignkey')
    op.drop_constraint(None, 'group_products', type_='foreignkey')
    # ### end Alembic commands ###
