"""add columns sale_value_varejo,sale_value_atacado and promotional

Revision ID: a81ac195772a
Revises: 160b3a8226cb
Create Date: 2022-02-15 18:38:31.534977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a81ac195772a'
down_revision = '160b3a8226cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sale_value_varejo', sa.Float(precision=2), nullable=False))
    op.add_column('products', sa.Column('sale_value_atacado', sa.Float(precision=2), nullable=False))
    op.add_column('products', sa.Column('sale_value_promotion', sa.Float(precision=2), nullable=True))
    op.add_column('products', sa.Column('date_start', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('date_end', sa.DateTime(), nullable=True))
    op.drop_column('products', 'sale_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sale_value', mysql.FLOAT(), nullable=False))
    op.drop_column('products', 'date_end')
    op.drop_column('products', 'date_start')
    op.drop_column('products', 'sale_value_promotion')
    op.drop_column('products', 'sale_value_atacado')
    op.drop_column('products', 'sale_value_varejo')
    # ### end Alembic commands ###
