"""create table storie

Revision ID: b1526b64f018
Revises: 29e665d1dc2e
Create Date: 2022-02-15 12:32:08.436422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1526b64f018'
down_revision = '29e665d1dc2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('street', sa.String(length=150), nullable=False))
    op.add_column('stores', sa.Column('number', sa.Integer(), nullable=False))
    op.add_column('stores', sa.Column('zip_code', sa.String(length=9), nullable=False))
    op.add_column('stores', sa.Column('other_information', sa.String(length=200), nullable=False))
    op.drop_column('stores', 'adress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('adress', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('stores', 'other_information')
    op.drop_column('stores', 'zip_code')
    op.drop_column('stores', 'number')
    op.drop_column('stores', 'street')
    # ### end Alembic commands ###
