"""create tables products and relationship

Revision ID: bc9af93b9a91
Revises: 
Create Date: 2022-02-10 20:17:28.866855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc9af93b9a91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorys',
    sa.Column('id_category', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_category'),
    sa.UniqueConstraint('name')
    )
    op.create_table('images_products',
    sa.Column('id_images', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_one', sa.String(length=100), nullable=True),
    sa.Column('image_two', sa.String(length=100), nullable=True),
    sa.Column('image_three', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_images')
    )
    op.create_table('products',
    sa.Column('id_product', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('id_images', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_category'], ['categorys.id_category'], ),
    sa.ForeignKeyConstraint(['id_images'], ['images_products.id_images'], ),
    sa.PrimaryKeyConstraint('id_product')
    )
    op.create_table('sizes_products',
    sa.Column('id_size', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_product'], ['products.id_product'], ),
    sa.PrimaryKeyConstraint('id_size')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sizes_products')
    op.drop_table('products')
    op.drop_table('images_products')
    op.drop_table('categorys')
    # ### end Alembic commands ###
