"""add forengkey in products for storie

Revision ID: cfba45427092
Revises: 8fba7f4a762a
Create Date: 2022-02-19 13:23:43.530153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfba45427092'
down_revision = '8fba7f4a762a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('id_store', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'stores', ['id_store'], ['id_store'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'id_store')
    # ### end Alembic commands ###
