"""create tadatabase

Revision ID: d1191bb92a01
Revises: ea56ad49ba86
Create Date: 2022-02-22 17:37:31.913514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1191bb92a01'
down_revision = 'ea56ad49ba86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products_base', 'image',
               existing_type=mysql.TEXT(),
               type_=sa.LargeBinary(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products_base', 'image',
               existing_type=sa.LargeBinary(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
