"""fix: add column sale_finish in orders 

Revision ID: dcd3b49e97f8
Revises: 2e097b20f83f
Create Date: 2022-04-11 21:06:24.542849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dcd3b49e97f8"
down_revision = "2e097b20f83f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("sale_finish", sa.Boolean(), nullable=False))
    op.alter_column(
        "orders_has_products",
        "sale_value",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "cost_value",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "sale_value_varejo",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "sale_value_atacado",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "sale_value_promotion",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "sale_value_promotion",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "products",
        "sale_value_atacado",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "sale_value_varejo",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "cost_value",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "orders_has_products",
        "sale_value",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.drop_column("orders", "sale_finish")
    # ### end Alembic commands ###
